//! Independent fixed-axis renderers. No external post source is embedded or
//! executed. Machine-builder macros and rotary functions are deliberately absent.
use super::*;
use crate::{CamArcPlane, CamMachineToolCallDto};

pub(super) fn render(
    document: &CamDocumentDto,
    program: &CamProgramDto,
    post: &CamPostConfigDto,
    name: &str,
    units: PostUnits,
) -> Result<String, CamPlanError> {
    let dialect = post.dialect;
    let conversational = matches!(
        dialect,
        PostDialect::Heidenhain | PostDialect::HermleHeidenhain
    );
    let osp = dialect == PostDialect::Okuma;
    let z = post.machine_retract_z.ok_or_else(|| {
        CamPlanError("Set Machine retract Z before posting this controller.".into())
    })?;
    if !z.is_finite() {
        return Err(CamPlanError("Machine retract Z must be finite".into()));
    }
    let number = post.program_number.unwrap_or(1001);
    let max_program = if dialect == PostDialect::Haas {
        99_999
    } else {
        9_999
    };
    if number == 0 || number > max_program {
        return Err(CamPlanError(format!("Program number must be 1–{max_program} for this fixed-axis post; it is never truncated.")));
    }
    let mut w = Writer {
        lines: vec![],
        numbered: post.sequence_numbers,
        conversational,
        sequence: 0,
    };
    let mut position: Option<Point3Dto> = None;
    let mut active_number = None;
    let mut active_tool = false;
    let mut approach = true;
    let mut offset: Option<WorkOffset> = None;
    let mut pending: Option<String> = None;
    let mut compensation = "R0";
    let mut used_calls = BTreeMap::new();
    for command in &program.commands {
        match command {
            CamCommandDto::ProgramStart { .. } => {
                if conversational {
                    w.block(format!(
                        "BEGIN PGM {number} {}",
                        if units.units == CamUnits::Inches {
                            "INCH"
                        } else {
                            "MM"
                        }
                    ));
                } else {
                    if !osp {
                        w.raw("%");
                    }
                    w.raw(&format!("O{number:04}"));
                }
                w.comment(name);
                w.comment("GENERATED BY LIMO CAD - VERIFY AND DRY RUN");
                w.comment(match dialect {
                    PostDialect::Fanuc => "LIMO CAD POST FANUC",
                    PostDialect::Haas => "LIMO CAD POST HAAS",
                    PostDialect::Mitsubishi => "LIMO CAD POST MITSUBISHI",
                    PostDialect::Mazak => "LIMO CAD POST MAZAK",
                    PostDialect::Syntec => "LIMO CAD POST SYNTEC",
                    PostDialect::Okuma => "LIMO CAD POST OSP",
                    _ => "LIMO CAD POST TNC",
                });
                if !conversational {
                    w.block(format!("G90 G17 {} G94 G40 G80", units.iso_mode_word()));
                }
                w.block("M5");
                w.block("M9");
            }
            CamCommandDto::WorkOffset { offset: next } => {
                if offset.is_some() && offset != Some(*next) {
                    retract(&mut w, dialect, units, z);
                    position = None;
                    approach = true;
                }
                if conversational {


                    w.block(format!(
                        "CYCL DEF 247 DATUM SETTING ~\n Q339=+{}",
                        next.index() + 1
                    ));
                } else if osp {
                    w.block(format!("G15 H{}", next.index() + 1));
                } else {
                    w.block(next.code());
                }
                offset = Some(*next);
            }
            CamCommandDto::SectionStart { name, .. } => w.comment(name),
            CamCommandDto::ToolChange { tool_id, .. } => {
                if pending.is_some() || compensation != "R0" {
                    return Err(CamPlanError(
                        "Tool change during cutter compensation".into(),
                    ));
                }
                let tool = document
                    .tool(*tool_id)
                    .ok_or_else(|| CamPlanError("Missing project tool".into()))?;
                let call =
                    crate::tool_calls::library_tool_call(tool, post.tool_call_mode, conversational)
                        .map_err(CamPlanError)?;
                if matches!(&call, CamMachineToolCallDto::Number { number } if *number > 99_999) {
                    return Err(CamPlanError("This starter post supports library tool numbers up to 99999; larger tool tables need a machine-specific implementation.".into()));
                }
                if dialect == PostDialect::Mazak && tool.number.is_some_and(|n| n > 512) {
                    return Err(CamPlanError("This Mazak EIA post uses the library tool number for H/D and supports registers 1–512.".into()));
                }
                if dialect == PostDialect::Haas && tool.number.is_some_and(|n| n > 200) {
                    return Err(CamPlanError("This Haas NGC starter uses the library tool number for H/D and supports registers 1–200.".into()));
                }
                let word = match &call {
                    CamMachineToolCallDto::Number { number } => number.to_string(),
                    CamMachineToolCallDto::Name { name } => format!("\"{name}\""),
                };
                if used_calls
                    .insert(word.clone(), *tool_id)
                    .is_some_and(|id| id != *tool_id)
                {
                    return Err(CamPlanError(format!(
                        "Tool call {word} is duplicated in the project tool library"
                    )));
                }
                active_number = tool.number;
                w.block("M5");
                w.block("M9");
                retract(&mut w, dialect, units, z);
                w.comment(&tool.name);
                if conversational {
                    w.block(format!("TOOL CALL {word} Z"));


                    retract(&mut w, dialect, units, z);
                } else {

                    w.block(if osp { "G53" } else { "G49" });
                    w.block(format!("T{word} M6"));
                }
                active_tool = true;
                approach = true;
                position = None;
            }
            CamCommandDto::Spindle { direction, rpm } => {
                let code = match direction {
                    SpindleDirection::Off => 5,
                    SpindleDirection::Clockwise => 3,
                    SpindleDirection::Counterclockwise => 4,
                };
                if code == 5 {
                    w.block("M5");
                } else if conversational {
                    w.block(format!("TOOL CALL Z S{rpm}"));
                    w.block(format!("M{code}"));
                } else {
                    w.block(format!("S{rpm} M{code}"));
                }
            }
            CamCommandDto::Coolant { mode } => {


                match mode {
                    CoolantMode::Off => w.block("M9"),
                    CoolantMode::Flood => w.block("M8"),
                    CoolantMode::Mist => return Err(CamPlanError("This brand post supports flood/off coolant only. Mist requires a machine-specific implementation.".into())),
                }
            }
            CamCommandDto::Rapid { to } | CamCommandDto::Linear { to, .. } => {
                if !active_tool {
                    return Err(CamPlanError("Motion before a tool call".into()));
                }
                let feed = match command {
                    CamCommandDto::Linear { feed, .. } => Some(*feed),
                    _ => None,
                };
                if pending.is_some() && feed.is_none() {
                    return Err(CamPlanError(
                        "Cutter compensation changes require a linear feed move".into(),
                    ));
                }
                if approach {
                    if pending.is_some() {
                        return Err(CamPlanError(
                            "Cutter compensation cannot start on the initial approach".into(),
                        ));
                    }
                    let f = feed
                        .map(|v| format!("F{}", units.feed(v)))
                        .unwrap_or_else(|| "FMAX".into());
                    if conversational {
                        w.block(format!(
                            "L X{} Y{} R0 {f}",
                            signed(units, to.x),
                            signed(units, to.y)
                        ));
                        w.block(format!("L Z{} R0 {f}", signed(units, to.z)));
                    } else {
                        let g = if feed.is_some() { "G1" } else { "G0" };
                        let fw = feed
                            .map(|v| format!(" F{}", units.feed(v)))
                            .unwrap_or_default();
                        let h = active_number.ok_or_else(|| {
                            CamPlanError("Tool-length offset needs a library tool number".into())
                        })?;
                        w.block(format!("{g} X{} Y{}{fw}", units.len(to.x), units.len(to.y)));
                        w.block(format!(
                            "{g} {} Z{} H{h}{fw}",
                            if osp { "G56" } else { "G43" },
                            units.len(to.z)
                        ));
                    }
                    approach = false;
                } else if conversational {
                    if let Some(words) = pending.take() {
                        compensation = match words.as_str() {
                            "RL" => "RL",
                            "RR" => "RR",
                            _ => "R0",
                        };
                    }
                    let f = feed
                        .map(|v| format!("F{}", units.feed(v)))
                        .unwrap_or_else(|| "FMAX".into());
                    w.block(format!(
                        "L X{} Y{} Z{} {compensation} {f}",
                        signed(units, to.x),
                        signed(units, to.y),
                        signed(units, to.z)
                    ));
                } else {
                    let c = pending
                        .take()
                        .map(|s| {
                            compensation = if s == "G40" { "R0" } else { "active" };
                            format!("{s} ")
                        })
                        .unwrap_or_default();
                    let f = feed
                        .map(|v| format!(" F{}", units.feed(v)))
                        .unwrap_or_default();
                    w.block(format!(
                        "{} {c}X{} Y{} Z{}{f}",
                        if feed.is_some() { "G1" } else { "G0" },
                        units.len(to.x),
                        units.len(to.y),
                        units.len(to.z)
                    ));
                }
                position = Some(*to);
            }
            CamCommandDto::Circular {
                clockwise,
                plane,
                center,
                to,
                feed,
            } => {
                let from = position
                    .filter(|_| !approach)
                    .ok_or_else(|| CamPlanError("Arc needs an established approach".into()))?;
                if pending.is_some() {
                    return Err(CamPlanError(
                        "Cutter compensation changes require a linear move".into(),
                    ));
                }


                if *plane != CamArcPlane::Xy {
                    return Err(CamPlanError(
                        "These fixed-axis posts currently accept XY arcs only".into(),
                    ));
                }
                if conversational && (to.z - from.z).abs() > 1e-9 {
                    for p in helix_points(from, *center, *to, *clockwise)? {
                        w.block(format!(
                            "L X{} Y{} Z{} {compensation} F{}",
                            signed(units, p.x),
                            signed(units, p.y),
                            signed(units, p.z),
                            units.feed(*feed)
                        ));
                    }
                } else if conversational {
                    w.block(format!(
                        "CC X{} Y{}",
                        signed(units, center.x),
                        signed(units, center.y)
                    ));
                    w.block(format!(
                        "C X{} Y{} DR{} {compensation} F{}",
                        signed(units, to.x),
                        signed(units, to.y),
                        if *clockwise { "-" } else { "+" },
                        units.feed(*feed)
                    ));
                } else {
                    w.block(format!(
                        "{} X{} Y{} Z{} I{} J{} F{}",
                        if *clockwise { "G2" } else { "G3" },
                        units.len(to.x),
                        units.len(to.y),
                        units.len(to.z),
                        units.len(center.x - from.x),
                        units.len(center.y - from.y),
                        units.feed(*feed)
                    ));
                }
                position = Some(*to);
            }
            CamCommandDto::Dwell { seconds } => {
                if !seconds.is_finite() || *seconds < 0.0 || *seconds > 99999.0 {
                    return Err(CamPlanError(
                        "Dwell is outside the post's supported range".into(),
                    ));
                }
                if conversational {
                    w.block("CYCL DEF 9.0 DWELL TIME");
                    w.block(format!("CYCL DEF 9.1 DWELL {}", decimal(*seconds, 3)));
                } else if osp {
                    w.block(format!("G4 F{}", real(*seconds)));
                } else if dialect == PostDialect::Haas {
                    w.block(format!("G4 P{}", real(*seconds)));
                } else {
                    let milliseconds = (*seconds * 1000.0).round() as u64;
                    let max = if matches!(dialect, PostDialect::Fanuc | PostDialect::Mitsubishi) {
                        9999
                    } else {
                        99_999_999
                    };
                    if milliseconds > max {
                        return Err(CamPlanError(format!(
                            "Dwell exceeds this post's {max} ms limit"
                        )));
                    }
                    w.block(format!("G4 P{milliseconds}"));
                }
            }
            CamCommandDto::CutterCompensationOn { left } => {
                if pending.is_some() || compensation != "R0" {
                    return Err(CamPlanError(
                        "Overlapping cutter compensation changes".into(),
                    ));
                }
                if osp && active_number.is_some_and(|n| n > 999) {
                    return Err(CamPlanError(
                        "This OSP post supports cutter-radius registers D1–D999".into(),
                    ));
                }
                pending = Some(if conversational {
                    if *left { "RL" } else { "RR" }.into()
                } else {
                    format!(
                        "{} D{}",
                        if *left { "G41" } else { "G42" },
                        active_number.ok_or_else(|| CamPlanError(
                            "Compensation needs a numbered tool".into()
                        ))?
                    )
                });
            }
            CamCommandDto::CutterCompensationOff => {
                pending = Some(if conversational { "R0" } else { "G40" }.into())
            }
            CamCommandDto::SetPosition { .. } => {
                return Err(CamPlanError(
                    "Simulator-only position reset cannot be posted".into(),
                ))
            }
            CamCommandDto::SectionEnd => {}
            CamCommandDto::ProgramEnd => {
                if pending.is_some() || compensation != "R0" {
                    return Err(CamPlanError(
                        "Program ends with active cutter compensation".into(),
                    ));
                }
                w.block("M9");
                w.block("M5");
                retract(&mut w, dialect, units, z);
                if !conversational {
                    w.block(if osp { "G53" } else { "G49" });
                }
                w.block("M30");
                if conversational {
                    w.block(format!(
                        "END PGM {number} {}",
                        if units.units == CamUnits::Inches {
                            "INCH"
                        } else {
                            "MM"
                        }
                    ));
                } else if !osp {
                    w.raw("%");
                }
            }
        }
        if w.lines.len() > 1_000_000 {
            return Err(CamPlanError(
                "Post exceeds the one-million-block output limit".into(),
            ));
        }
        let maximum_sequence = match dialect {
            PostDialect::Syntec => 8999,
            PostDialect::Haas => 99_999,
            _ => 99_999_999,
        };
        if w.sequence > maximum_sequence {
            return Err(CamPlanError(format!("Sequence numbers exceed this post's N{maximum_sequence} limit. Disable sequence numbers; they are never wrapped or duplicated.")));
        }
    }
    if pending.is_some() {
        return Err(CamPlanError("Unconsumed cutter compensation change".into()));
    }
    Ok(format!("{}\n", w.lines.join("\n")))
}

fn retract(w: &mut Writer, dialect: PostDialect, u: PostUnits, z: f64) {
    if w.conversational {
        w.block(format!("L Z{} R0 FMAX M91", signed(u, z)));
    } else if dialect == PostDialect::Okuma {
        w.block(format!("G16 H0 G0 Z{}", u.len(z)));
    } else {
        w.block(format!("G90 G53 G0 Z{}", u.len(z)));
    }
}

fn signed(u: PostUnits, value: f64) -> String {
    let s = u.len(value);
    if s.starts_with('-') {
        s
    } else {
        format!("+{s}")
    }
}

fn real(value: f64) -> String {
    let s = decimal(value, 3);
    if s.contains('.') {
        s
    } else {
        format!("{s}.0")
    }
}

pub(super) fn helix_points(
    from: Point3Dto,
    center: Point3Dto,
    to: Point3Dto,
    clockwise: bool,
) -> Result<Vec<Point3Dto>, CamPlanError> {
    let r = (from.x - center.x).hypot(from.y - center.y);
    let end_radius = (to.x - center.x).hypot(to.y - center.y);
    if !from.is_finite() || !center.is_finite() || !to.is_finite() || !r.is_finite() || r <= 1e-9 {
        return Err(CamPlanError(
            "Helix must be finite with a positive radius".into(),
        ));
    }
    if (r - end_radius).abs() > 1e-6 {
        return Err(CamPlanError("Helix endpoints disagree on radius".into()));
    }
    let start = (from.y - center.y).atan2(from.x - center.x);
    let end = (to.y - center.y).atan2(to.x - center.x);
    let direction = if clockwise { -1.0 } else { 1.0 };
    let mut sweep = ((end - start) * direction).rem_euclid(std::f64::consts::TAU);
    if sweep < 1e-10 {
        sweep = std::f64::consts::TAU;
    }

    let angle = (2.0 * (1.0 - (0.002 / r).min(1.0)).acos()).min(5_f64.to_radians());
    let count = (sweep / angle.max(1e-8)).ceil() as usize;
    if count > 100_000 {
        return Err(CamPlanError(
            "Helix exceeds the bounded post tessellation limit".into(),
        ));
    }
    Ok((1..=count.max(1))
        .map(|i| {
            if i == count {
                to
            } else {
                let t = i as f64 / count as f64;
                let a = start + direction * sweep * t;
                Point3Dto::new(
                    center.x + r * a.cos(),
                    center.y + r * a.sin(),
                    from.z + (to.z - from.z) * t,
                )
            }
        })
        .collect())
}

struct Writer {
    lines: Vec<String>,
    numbered: bool,
    conversational: bool,
    sequence: usize,
}
impl Writer {
    fn raw(&mut self, line: &str) {
        self.lines.push(line.into());
    }
    fn block(&mut self, line: impl AsRef<str>) {
        let line = line.as_ref();
        if self.conversational {
            self.lines.push(format!("{} {line}", self.lines.len()));
        } else if self.numbered {
            self.sequence += 1;
            self.lines.push(format!("N{} {line}", self.sequence));
        } else {
            self.raw(line);
        }
    }
    fn comment(&mut self, text: &str) {
        let clean: String = text
            .chars()
            .take(80)
            .map(|c| {
                if c.is_ascii_graphic() && !matches!(c, '(' | ')' | ';' | '%') {
                    c
                } else {
                    ' '
                }
            })
            .collect();
        if self.conversational {
            self.block(format!("; {}", clean.trim()));
        } else {
            self.raw(&format!("({})", clean.trim()));
        }
    }
}
