use super::*;
use crate::{
    simulate_gcode, simulate_setup, CamGcodeDialectDto, CamGcodeSimulationRequestDto,
    CamMachineAssignmentDto, CamSimulationRequestDto, CamToolCallMode,
};

const BRANDS: &[PostDialect] = &[
    PostDialect::Fanuc,
    PostDialect::Haas,
    PostDialect::Mitsubishi,
    PostDialect::Mazak,
    PostDialect::Syntec,
    PostDialect::Okuma,
    PostDialect::Heidenhain,
    PostDialect::HermleHeidenhain,
];

fn fixture(dialect: PostDialect) -> CamDocumentDto {
    let mut doc = tests::document(dialect);
    doc.post_defaults.machine_retract_z = Some(-2.0);
    doc.setups[0].machine = Some(CamMachineAssignmentDto::three_axis(
        doc.post_defaults.clone(),
    ));
    doc
}
fn request() -> CamPostRequestDto {
    CamPostRequestDto {
        setup_id: 1,
        post: None,
        program_name: Some("BRAND_TEST".into()),
    }
}

#[test]
fn all_brands_have_distinct_contracts_without_optional_stop_or_custom_macros() {
    for &dialect in BRANDS {
        let mut doc = fixture(dialect);
        doc.setups[0].work_offset_count = 2;
        let mut second_tool = doc.tools[0].clone();
        second_tool.id = 2;
        second_tool.number = Some(2);
        second_tool.name = "SecondMill".into();
        doc.tools.push(second_tool);
        doc.next_tool_id = 3;
        let mut second_operation = doc.setups[0].operations[0].clone();
        if let crate::CamOperationDto::Face {
            id, tool_id, name, ..
        } = &mut second_operation
        {
            *id = 2;
            *tool_id = 2;
            *name = "Second facing".into();
        }
        doc.setups[0].operations.push(second_operation);
        doc.next_operation_id = 3;
        let posted = post_setup(&doc, &request()).unwrap();
        assert!(posted.nc.contains("GENERATED BY LIMO CAD"));
        assert!(!posted.nc.contains("NOBS CAD"));
        assert_eq!(posted.dialect, dialect);
        assert_eq!(posted.extension, dialect.extension());
        let words: Vec<_> = posted.nc.split_whitespace().collect();
        assert!(!words.contains(&"M1"));
        assert!(!words.contains(&"G81"));
        assert!(!words.contains(&"G83"));
        if matches!(
            dialect,
            PostDialect::Heidenhain | PostDialect::HermleHeidenhain
        ) {
            assert!(posted.nc.starts_with("0 BEGIN PGM 42 MM\n"));
            assert!(posted.nc.contains("TOOL CALL 1 Z"));
            assert!(posted.nc.contains("TOOL CALL 2 Z"));
            assert!(posted.nc.contains("Q339=+1") && posted.nc.contains("Q339=+2"));
            assert!(
                posted.nc.contains("DATUM SETTING ~\n Q339=+1"),
                "cycle parameters continue the same unnumbered block"
            );
            assert!(posted.nc.contains("L Z-2 R0 FMAX M91"));
            assert!(posted.nc.contains("END PGM 42 MM"));
            assert!(posted
                .warnings
                .iter()
                .any(|w| w.contains("does not yet interpret")));
        } else if dialect == PostDialect::Okuma {
            assert!(posted.nc.contains("T2 M6"));
            assert!(posted.nc.starts_with("O0042\n"));
            assert!(posted.nc.contains("G15 H1") && posted.nc.contains("G15 H2"));
            assert!(posted.nc.contains("G16 H0 G0 Z-2"));
            assert!(posted
                .nc
                .lines()
                .any(|l| l.starts_with("G0 G56 Z") && l.ends_with(" H1")));
            assert!(!posted.nc.contains("G43"));
        } else {
            assert!(posted.nc.contains("T2 M6"));
            assert!(posted.nc.starts_with("%\nO0042\n"));
            assert!(posted.nc.contains("G90 G53 G0 Z-2"));
            assert!(posted
                .nc
                .lines()
                .any(|l| l.starts_with("G0 G43 Z") && l.ends_with(" H1")));
            let lines = posted.nc.lines().collect::<Vec<_>>();
            for (i, line) in lines.iter().enumerate() {
                if line.contains("G43 Z") {
                    assert!(lines[i - 1].starts_with("G0 X") && !lines[i - 1].contains(" Z"));
                }
                if *line == "T1 M6" || *line == "T2 M6" {
                    assert_eq!(lines[i - 1], "G49");
                    assert!(lines[i - 2].starts_with('('));
                    assert!(lines[i - 3].starts_with("G90 G53 G0 Z"));
                }
            }
        }
    }
}

#[test]
fn missing_retract_wrong_family_missing_number_and_invalid_program_fail_closed() {
    for &dialect in BRANDS {
        let mut doc = fixture(dialect);
        doc.setups[0]
            .machine
            .as_mut()
            .unwrap()
            .profile
            .post
            .machine_retract_z = None;
        assert!(post_setup(&doc, &request())
            .unwrap_err()
            .to_string()
            .contains("Machine retract Z"));
        doc.setups[0]
            .machine
            .as_mut()
            .unwrap()
            .profile
            .post
            .machine_retract_z = Some(0.0);
        doc.setups[0]
            .machine
            .as_mut()
            .unwrap()
            .profile
            .post
            .program_number = Some(100_001);
        assert!(post_setup(&doc, &request())
            .unwrap_err()
            .to_string()
            .contains("never truncated"));
    }
    let mut doc = fixture(PostDialect::Haas);
    doc.tools[0].number = None;
    assert!(post_setup(&doc, &request())
        .unwrap_err()
        .to_string()
        .contains("needs a number"));
    doc.tools[0].number = Some(1);
    doc.setups[0]
        .machine
        .as_mut()
        .unwrap()
        .profile
        .post
        .tool_call_mode = CamToolCallMode::Name;
    assert!(post_setup(&doc, &request())
        .unwrap_err()
        .to_string()
        .contains("requires numeric"));
}

#[test]
fn offset_register_and_sequence_bounds_never_truncate_or_wrap() {
    let mut haas = fixture(PostDialect::Haas);
    haas.tools[0].number = Some(201);
    assert!(post_setup(&haas, &request())
        .unwrap_err()
        .to_string()
        .contains("1–200"));
    let mut mazak = fixture(PostDialect::Mazak);
    mazak.tools[0].number = Some(513);
    assert!(post_setup(&mazak, &request())
        .unwrap_err()
        .to_string()
        .contains("1–512"));
    let mut osp = tests::contour_document(PostDialect::Okuma);
    osp.tools[0].number = Some(1000);
    osp.setups[0].machine = Some(CamMachineAssignmentDto::three_axis(
        osp.post_defaults.clone(),
    ));
    assert!(post_setup(&osp, &request())
        .unwrap_err()
        .to_string()
        .contains("D1–D999"));
    let mut doc = fixture(PostDialect::Syntec);
    doc.post_defaults.sequence_numbers = true;
    let mut program = plan_setup(&doc, 1).unwrap();
    let end = program.commands.pop().unwrap();
    program.commands.extend(std::iter::repeat_n(
        CamCommandDto::Dwell { seconds: 0.1 },
        8999,
    ));
    program.commands.push(end);
    let units = PostUnits {
        units: CamUnits::Millimeters,
        contains_arcs: false,
    };
    assert!(
        brand_posts::render(&doc, &program, &doc.post_defaults, "LIMIT", units)
            .unwrap_err()
            .to_string()
            .contains("never wrapped")
    );
    doc.post_defaults.sequence_numbers = false;
    assert!(brand_posts::render(&doc, &program, &doc.post_defaults, "LIMIT", units).is_ok());
}

#[test]
fn names_are_exact_and_numbers_are_preferred_without_separate_bindings() {
    for dialect in [
        PostDialect::Siemens828d,
        PostDialect::Heidenhain,
        PostDialect::HermleHeidenhain,
    ] {
        let mut doc = fixture(dialect);
        doc.tools[0].name = "EndMill_a".into();
        doc.tools[0].number = Some(17);
        doc.setups[0].machine.as_mut().unwrap().tool_calls.clear();
        let posted = post_setup(&doc, &request()).unwrap();
        assert!(posted
            .nc
            .lines()
            .any(|l| l == "T17" || l.contains("TOOL CALL 17 Z")));
        doc.setups[0]
            .machine
            .as_mut()
            .unwrap()
            .profile
            .post
            .tool_call_mode = CamToolCallMode::Name;
        let named = post_setup(&doc, &request()).unwrap();
        assert!(named.nc.contains("\"EndMill_a\""));
        assert!(!named.nc.contains("\"ENDMILL_A\""));
        doc.tools[0].name = "bad\"\nM30".into();
        assert!(post_setup(&doc, &request()).is_err());
    }
}

#[test]
fn iso_brand_roundtrips_keep_cutting_stock_mm_inches_arcs_and_work_offsets() {
    for dialect in [
        PostDialect::Fanuc,
        PostDialect::Haas,
        PostDialect::Mitsubishi,
        PostDialect::Mazak,
        PostDialect::Syntec,
    ] {
        for units in [CamUnits::Millimeters, CamUnits::Inches] {
            let mut doc = tests::contour_document(dialect);
            doc.units = units;
            doc.post_defaults.machine_retract_z = Some(-2.0);
            doc.setups[0].machine = Some(CamMachineAssignmentDto::three_axis(
                doc.post_defaults.clone(),
            ));
            doc.setups[0].work_offset_count = 2;
            let posted = post_setup(&doc, &request()).unwrap();
            let cam = simulate_setup(
                &doc,
                &CamSimulationRequestDto {
                    setup_id: 1,
                    voxel_size: Some(0.5),
                    max_voxels: None,
                    stock_mesh: None,
                    target: None,
                    through_operation_id: None,
                    completed_steps: None,
                    playback_time_seconds: None,
                },
            )
            .unwrap();
            let nc = simulate_gcode(
                &doc,
                &CamGcodeSimulationRequestDto {
                    setup_id: 1,
                    source: posted.nc,
                    file_name: Some("test.nc".into()),
                    dialect: CamGcodeDialectDto::Auto,
                    voxel_size: Some(0.5),
                    max_voxels: None,
                    stock_mesh: None,
                    target: None,
                    completed_steps: None,
                },
            )
            .unwrap();
            assert_eq!(
                cam.remaining_voxels, nc.remaining_voxels,
                "{dialect:?} {units:?}"
            );
            assert_eq!(
                cam.collisions.len(),
                nc.collisions.len(),
                "{dialect:?} {units:?}"
            );
        }
    }
}

#[test]
fn dwell_units_are_explicit_and_auto_replay_does_not_reinterpret_them() {
    for &dialect in BRANDS {
        let doc = fixture(dialect);
        let mut program = plan_setup(&doc, 1).unwrap();
        program.commands.insert(
            program.commands.len() - 1,
            CamCommandDto::Dwell { seconds: 1.5 },
        );
        let nc = brand_posts::render(
            &doc,
            &program,
            &doc.post_defaults,
            "TEST",
            PostUnits {
                units: CamUnits::Millimeters,
                contains_arcs: false,
            },
        )
        .unwrap();
        let expected = match dialect {
            PostDialect::Haas => "G4 P1.5",
            PostDialect::Okuma => "G4 F1.5",
            PostDialect::Heidenhain | PostDialect::HermleHeidenhain => "CYCL DEF 9.1 DWELL 1.5",
            _ => "G4 P1500",
        };
        assert!(nc.contains(expected), "{dialect:?}");
        let request = CamGcodeSimulationRequestDto {
            setup_id: 1,
            source: nc,
            file_name: Some(format!("test.{}", dialect.extension())),
            dialect: CamGcodeDialectDto::Auto,
            voxel_size: Some(0.5),
            max_voxels: None,
            stock_mesh: None,
            target: None,
            completed_steps: None,
        };
        let replay = simulate_gcode(&doc, &request);
        if matches!(
            dialect,
            PostDialect::Okuma | PostDialect::Heidenhain | PostDialect::HermleHeidenhain
        ) {
            assert!(replay
                .unwrap_err()
                .to_string()
                .contains("does not yet interpret"));
        } else {
            let sim = replay.unwrap();
            let dwell = sim
                .steps
                .iter()
                .find(|s| s.kind == crate::CamSimulationStepKind::Dwell)
                .unwrap();
            assert!((dwell.duration_seconds - 1.5).abs() < 1e-9);
            let mut wrong = request.clone();
            wrong.dialect = CamGcodeDialectDto::Iso;
            assert!(simulate_gcode(&doc, &wrong)
                .unwrap_err()
                .to_string()
                .contains("conflicts"));
        }
    }
}

#[test]
fn conversational_helix_chords_bound_error_and_preserve_endpoint_direction_and_depth() {
    for radius in [0.01, 1.0, 100.0, 10000.0] {
        for clockwise in [false, true] {
            for full_circle in [false, true] {
                let from = Point3Dto::new(radius, 0.0, 5.0);
                let center = Point3Dto::new(0.0, 0.0, 5.0);
                let to = if full_circle {
                    Point3Dto::new(radius, 0.0, -2.0)
                } else {
                    Point3Dto::new(0.0, radius, -2.0)
                };
                let points = brand_posts::helix_points(from, center, to, clockwise).unwrap();
                assert_eq!(points.last(), Some(&to));
                let mut previous = from;
                for p in points {
                    let midpoint_radius =
                        ((p.x + previous.x) / 2.0).hypot((p.y + previous.y) / 2.0);
                    assert!(radius - midpoint_radius <= 0.002 + 1e-9);
                    assert!(p.z < previous.z);
                    let cross = previous.x * p.y - previous.y * p.x;
                    assert!(if clockwise { cross < 0.0 } else { cross > 0.0 });
                    previous = p;
                }
            }
        }
    }
    assert!(brand_posts::helix_points(
        Point3Dto::new(1.0, 0.0, 0.0),
        Point3Dto::new(0.0, 0.0, 0.0),
        Point3Dto::new(0.0, 2.0, -1.0),
        false
    )
    .is_err());
}

#[test]
fn haas_dwell_integer_and_decimal_words_have_different_units() {
    let doc = fixture(PostDialect::Haas);
    for (word, seconds) in [("10", 0.01), ("10.", 10.0), ("1.5", 1.5)] {
        let req = CamGcodeSimulationRequestDto {
            setup_id: 1,
            source: format!("T1 M6\nG21 G90\nG0 X0 Y0 Z10\nG1 X1 F100\nG4 P{word}\nM30"),
            file_name: None,
            dialect: CamGcodeDialectDto::Haas,
            voxel_size: Some(0.5),
            max_voxels: None,
            stock_mesh: None,
            target: None,
            completed_steps: None,
        };
        let sim = simulate_gcode(&doc, &req).unwrap();
        let dwell = sim
            .steps
            .iter()
            .find(|s| s.kind == crate::CamSimulationStepKind::Dwell)
            .unwrap();
        assert!((dwell.duration_seconds - seconds).abs() < 1e-9);
    }
}
